import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import InputBox from "./components/Input";
import SwitchUnit from "./components/SwitchUnit";
import Link from "next/link";
import Lottie from "lottie-react";
import weatherAnimation from "./components/lottieFiles/weatherAnimation.json";
import LottieFiles from "./components/lottieFiles/lottieFiles";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Weather.AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>
          <div className="h-full">
            <div className="md:pl-44 pl-4 flex mt-6 text-2xl justify-between">
              <div className="flex h-12 space-x-6">
                <span>weather.ai</span>
                <LottieFiles animation={weatherAnimation} />
              </div>
              <div className="flex space-x-4">
                <InputBox />
                <SwitchUnit />
              </div>
            </div>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
